#Durex class mapping
#Sun May 03 21:27:29 CEST 2026
pl.durex.client.DurexClient=pl.durex.client.DurexClient
pl.durex.client.config.DurexConfig=pl.durex.client.config.DurexConfig
pl.durex.client.gui.ConfigScreen=pl.durex.client.gui.ConfigScreen
pl.durex.client.gui.DurexClickGuiScreen=pl.durex.client.gui.DurexClickGuiScreen
pl.durex.client.gui.DurexClickGuiScreen$CategoryWidget=pl.durex.client.gui.DurexClickGuiScreen$CategoryWidget
pl.durex.client.gui.DurexClickGuiScreen$ModDef=pl.durex.client.gui.DurexClickGuiScreen$ModDef
pl.durex.client.gui.DurexClickGuiScreen$ModWidget=pl.durex.client.gui.DurexClickGuiScreen$ModWidget
pl.durex.client.gui.TracerEditorScreen=pl.durex.client.gui.TracerEditorScreen
pl.durex.client.gui.render.GuiRenderUtils=pl.durex.client.gui.render.GuiRenderUtils
pl.durex.client.license.LicenseManager=pl.durex.client.license.LicenseManager
pl.durex.client.license.LicenseScreen=pl.durex.client.license.LicenseScreen
pl.durex.client.loader.LicenceClassLoader=x.a
pl.durex.client.loader.ModuleProcessor=x.b
pl.durex.client.loader.ModuleUpdater=x.c
pl.durex.client.mixin.EntityGlowMixin=pl.durex.client.mixin.EntityGlowMixin
pl.durex.client.mixin.EntityRenderDispatcherMixin=pl.durex.client.mixin.EntityRenderDispatcherMixin
pl.durex.client.mixin.GameRendererMixin=pl.durex.client.mixin.GameRendererMixin
pl.durex.client.mixin.GuiBlurMixin=pl.durex.client.mixin.GuiBlurMixin
pl.durex.client.mixin.HeldItemRendererMixin=pl.durex.client.mixin.HeldItemRendererMixin
pl.durex.client.mixin.HideVanillaNametagMixin=pl.durex.client.mixin.HideVanillaNametagMixin
pl.durex.client.mixin.InGameHudMixin=pl.durex.client.mixin.InGameHudMixin
pl.durex.client.mixin.ItemCooldownAccessor=pl.durex.client.mixin.ItemCooldownAccessor
pl.durex.client.mixin.LeverCobwebMixin=pl.durex.client.mixin.LeverCobwebMixin
pl.durex.client.mixin.MinecraftClientAccessor=pl.durex.client.mixin.MinecraftClientAccessor
pl.durex.client.mixin.MsgBotChatMixin=pl.durex.client.mixin.MsgBotChatMixin
pl.durex.client.mixin.MsgBotPauseMixin=pl.durex.client.mixin.MsgBotPauseMixin
pl.durex.client.mixin.MsgBotScreenHandlerMixin=pl.durex.client.mixin.MsgBotScreenHandlerMixin
pl.durex.client.mixin.NoPushMixin=pl.durex.client.mixin.NoPushMixin
pl.durex.client.mixin.ProjectileUtilMixin=pl.durex.client.mixin.ProjectileUtilMixin
pl.durex.client.module.AntiKostkaModule=x.d
pl.durex.client.module.AntiKostkaModule$DelayMode=x.d$a
pl.durex.client.module.AntiKostkaModule$HotbarSlot=x.d$b
pl.durex.client.module.AntiKowalModule=x.e
pl.durex.client.module.AutoChHandler=x.f
pl.durex.client.module.AutoDripstoneModule=x.g
pl.durex.client.module.BombModule=x.h
pl.durex.client.module.CooldownHudModule=x.i
pl.durex.client.module.CooldownHudModule$CooldownEntry=x.i$a
pl.durex.client.module.CustomTracerStyle=x.j
pl.durex.client.module.FriendModule=x.k
pl.durex.client.module.LeverCobwebModule=x.l
pl.durex.client.module.LeverCobwebModule$FluidAccessMode=x.l$a
pl.durex.client.module.LeverCobwebModule$FluidSource=x.l$b
pl.durex.client.module.LeverCobwebModule$LeverHoldPlan=x.l$c
pl.durex.client.module.LeverCobwebModule$LeverHoldState=x.l$d
pl.durex.client.module.LeverCobwebModule$PendingSequence=x.l$e
pl.durex.client.module.LeverCobwebModule$PlacementPlan=x.l$f
pl.durex.client.module.LeverCobwebModule$SequenceStage=x.l$g
pl.durex.client.module.LeverCobwebModule$SpeedProfile=x.l$h
pl.durex.client.module.MsgBotModule=x.m
pl.durex.client.module.NametagRenderer=x.n
pl.durex.client.module.NametagsModule=x.o
pl.durex.client.module.NametagsModule$NametagData=x.o$a
pl.durex.client.module.NoPushModule=x.p
pl.durex.client.module.ProcenciarzModule=pl.durex.client.module.ProcenciarzModule
pl.durex.client.module.ProcenciarzModule$TargetInfo=pl.durex.client.module.ProcenciarzModule$TargetInfo
pl.durex.client.module.TracerModule=x.q
pl.durex.client.module.TracerModule$Style=x.q$a
pl.durex.client.module.TracerRenderer=x.r
pl.durex.client.module.TracerRenderer$1=x.r$1
pl.durex.client.module.ViewModelModule=x.s
pl.durex.client.module.ViewModelModule$Hand=x.s$a
pl.durex.client.module.ZbrojmistrzModule=pl.durex.client.module.ZbrojmistrzModule
pl.durex.client.module.ZbrojmistrzModule$ArmorInfo=pl.durex.client.module.ZbrojmistrzModule$ArmorInfo
pl.durex.client.module.ZbrojmistrzModule$ItemData=pl.durex.client.module.ZbrojmistrzModule$a
pl.durex.client.util.RaycastState=x.t
pl.durex.client.util.TimerUtil=x.u
